### ISSUE TITLE
neatmaps gives error 'heatmap' objects don't have these attributes: 'showlegend'

### ISSUE THREAD

**Issue by bharati-mehani** [PhilBoileau/neatmaps#3]
Hi All, while using neatmaps with consensusMap(neat_res) or neat_res$heatmap, I am getting following error:

'heatmap' objects don't have these attributes: 'showlegend'
Valid attributes include:
'type', 'visible', 'opacity', 'name', 'uid', 'ids', 'customdata', 'meta', 'hoverinfo', 'hoverlabel', 'stream', 'transforms', 'uirevision', 'z', 'x', 'x0', 'dx', 'y', 'y0', 'dy', 'text', 'hovertext', 'transpose', 'xtype', 'ytype', 'zsmooth', 'connectgaps', 'xgap', 'ygap', 'zhoverformat', 'hovertemplate', 'zauto', 'zmin', 'zmax', 'zmid', 'colorscale', 'autocolorscale', 'reversescale', 'showscale', 'colorbar', 'coloraxis', 'xcalendar', 'ycalendar', 'xaxis', 'yaxis', 'idssrc', 'customdatasrc', 'metasrc', 'hoverinfosrc', 'zsrc', 'xsrc', 'ysrc', 'textsrc', 'hovertextsrc', 'hovertemplatesrc', 'key', 'set', 'frame', 'transforms', '_isNestedKey', '_isSimpleKey', '_isGraticule', '_bbox'
Any help to solve this issue, will be highly appreciated.

Thanks

**Comment by PhilBoileau** [comment]
Hello. There appears to be an issue with `heatmaply`, the package that `neatmaps` uses to generate heatmaps. However, the code in `neatmaps`' `README.Rmd` doesn't produce an error on my machine, only a warning. Can you confirm that this is what's occurring? If so, it shouldn't cause any issues with `neatmaps`' plots. Otherwise, please provide your session information.
